### ISSUE TITLE
Some issues and suggestions

### ISSUE THREAD

**Issue by TKperson** [Ultra-SC/Ultra-SC#1]
Hello, I tried out your image anonymous hosting service - it looks great. But I would like to make a few suggestions. 

# User experience

### Overflowing elements
I have tested out the website on firefox, chrome, and safari(mobile). The versions on the PCs worked fine, until it gets to a thinner screen. The elements were overflowing the parent element.

![image0](https://user-images.githubusercontent.com/50115012/115629756-d3240480-a2b7-11eb-96e9-f6d069879ea0.png)

### Not properly handled animation/transition and alignment for the show menu button

This is located in the Doc of the image host service.

On computer: 

https://user-images.githubusercontent.com/50115012/115639620-ed66de00-a2c9-11eb-8118-b5196e3481cf.mp4

On mobile safari and chrome:

![image0](https://user-images.githubusercontent.com/50115012/115639659-02dc0800-a2ca-11eb-8972-0d9717335ad6.png)

![image1](https://user-images.githubusercontent.com/50115012/115639683-0ec7ca00-a2ca-11eb-83b6-dbb5de5bde9a.png)

### Not required console.log
After opening up a browser Javascript console I saw the image token were being logged. This really isn't a big issue. But I think since the image token were already being displayed in the website, then displaying it again in the console will be a waste of resources. (Yes ik it only takes away 0.00001% of computer resources)

<img width="388" alt="Screenshot 2021-04-21 154208" src="https://user-images.githubusercontent.com/50115012/115630049-3ada4f80-a2b8-11eb-8fba-913b13a23362.png">

### Dark mode for the home page
The home page of http://ultrasc.tk/ looks great, but it's still tilting to the light mode side. (Shines quite a bit in a dark room)

### Accessing the image

After looking through the Doc, I didn't see anything that explains how exactly, to access the images I uploaded. I have tried to use something like http://ultrasc.tk/img/id=123456 and http://ultrasc.tk/img/?id=1234
What are the paths before the endpoints?

### Request methods

For one of the delete image method stated in your Doc was:
<img width="425" alt="Screenshot 2021-04-21 162313" src="https://user-images.githubusercontent.com/50115012/115634214-fb166680-a2bd-11eb-886e-df62962cb026.png">

For better user experience I suggest that you can try to use the delete http request method. Here's a list of [http request methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods)

I hoping that it will look something like this for
```py
header = {'image-token': 'asdf'}
requests.delete('http://ultrasc.tk/img/?id=<Your_ID>')
# or
requests.delete('http://ultrasc.tk/img/?id=<Your_ID>&token=asdf')
```

And for getting the image. It should look something as simple as this:
```py
requests.get('http://ultrasc.tk/img/?id=<Your_ID>'')
```
### Text font suggestion

I realized the fonts are a little uneven. Check out this article taking about auto resizing fonts: https://fvsch.com/css-locks
And a demo of their auto resizing fonts: https://fvsch.com/articles/css-locks/demo1.html

# Security

I really couldn't find any major flaw in the frontend development. But I found a potential gateway for remote server access.

### How does this work?
First of all, when I look into the docs of this API, I found a really interest way of connecting to the API: ws://IPv4:3000

I then tried to paste the IPv4 into a browser. Surprisingly, the home website showed up. This is already a red flag because usually raw IPv4/IPv6 are not protected, which can lead to people DDoSing the server.

Later, I was curious about what's inside this IPv4 (I'm still in the "curious" stage of learning about CS), so I did a nmap scan(please don't be mad at me for using a scanner)

<img width="686" alt="Screenshot 2021-04-21 160026" src="https://user-images.githubusercontent.com/50115012/115631467-bb9a4b00-a2ba-11eb-9445-40ae627a3f9a.png">

The result surprised me even more. I saw a SSH port is right open and Cloudflare isn't protecting the raw IP. Opening SSH port has the potential to lead to malicious remote access. I tried to connect to it(you can probably see my fingerprint), and it looks like you can have unlimited tries for guessing the password, so people can launch a dictionary attack or brutal force their way into the server.

A quick fix would be close the ssh port and the ports that are not needed.

If you have time you can try implementing this: https://github.com/skeeto/endlessh - a very fun ssh port made for the script kiddies.

I'm looking forward to use this image hosting service :).

**Comment by DmitrijVC** [comment]
Hi, thanks for such detailed review.
It's important to notice that UltraSC is still in the beta version and has a lot of flaws which I am working on, but unfortunately I don't have much time to spend on this project to finish everything in couple of days.

# Frontend
As for the frontend, I am not responsible for it (except the docs). I am aware of some bugs and for sure it will be fixed.
Whole documentation page is temporary and should be changed in the future.
Also thanks for pointing out that home page needs more dark colours, we will redesign it. 

# Upload page
Honestly it shouldn't be released just yet, because of this issue with wss. 
I agree that upload JS script on this page is pretty "raw" and logs in the console are unnecessary, but for now my priority is to patch security issues, and fix wss module. 

# Accessing the image
> After looking through the Doc, I didn't see anything that explains how exactly, to access the images I uploaded. I have tried to use something like http://ultrasc.tk/img/id=123456 and http://ultrasc.tk/img/?id=1234
> What are the paths before the endpoints?

Now I see that I've made a mistake in the docs.
`/img/id=<ID>` shold be `/img?id=<ID>`, so if your image is a *PNG* and has id of *11* the whole url to access this image would be:
https://www.ultrasc.tk/img?id=11
and if you want the raw file:
https://www.ultrasc.tk/images/11.png

# Removing Images
> For better user experience I suggest that you can try to use the delete http request method. Here's a list of http request methods

This was a thing in the previous version
<img src="https://image.prntscr.com/image/B-C3JUOQSu6GeKP4O8ZNnQ.png">
I can bring it back, but I am going to ask around what others think about it first.

# Security
It's my first ever web service and security is expected to be a little "leaky", but thanks to your suggestions I might be able to patch some issues.

What is more, I don't have any experience with Cloudflare, so I may have forgotten to check some settings.

# Not mentioned
The python module for the UltraSC [**"ultra-py"**](https://github.com/Ultra-SC/ultra-py) is outdated and need a lot of tweaking, but for now there are much more important things to fix.

# Conclusion
Basing on the current status of UltraSC the most important thing is the security, which I am going to start fixing first. On the second place is the optimization and last but not least, style. 

# 
Thanks for your support, your opinion of the UltraSC service matters a lot.

**Comment by TKperson** [comment]
Hmm since I can see where the accessing image part is going. 
I can see that the ID is designed to be in order (it's cool to have a smaller ID than other people [it proves you are some kind of OG user]), but do you think people will fetch all of the images in your data base? Or even making a camp bot to camp at the most recent uploaded image(this can easily achieved by fetching the most recent image over a time interval), and then display it in a "stolen" database gallery that people can look through all of the images that are in there.

**Comment by TKperson** [comment]
I think it would be easier for people to access if this is something like `images/11/download`, `raw/image/11`, or `image/11?raw=true` instead of `images/11.png` 

Because if I'm going to make a program with the API, I don't want to deal with the file extensions.

**Comment by TKperson** [comment]
## No compression/change meta maybe is broken?

yay.jpg is original and 19.jpg is downloaded; 
<img width="441" alt="Screenshot 2021-04-22 175954" src="https://user-images.githubusercontent.com/50115012/115802884-94b04780-a394-11eb-9d6c-9cb5f5b7b395.png">

The file size got bigger after downloading it. And the data has been changed

Here's another picture of uploaded vs downloaded:
<img width="441" alt="Screenshot 2021-04-22 175954" src="https://user-images.githubusercontent.com/50115012/115823266-e53a9b80-a3ba-11eb-9ae9-9940a4c65831.png">

For the second one, it looks like the binary was completely rewritten.

**Comment by DmitrijVC** [comment]
> Do you think people will fetch all of the images in your database? Or even making a camp bot to camp at the most recent uploaded image(this can easily achieved by fetching the most recent image over a time interval), and then display it in a "stolen" database gallery that people can look through all of the images that are in there.

Storing images in this way was intended and probably won't be changed, unless I change my mind before releasing the 1.0 version. Hidden images will be a thing in the future where it can't be accessed without providing the token. 
What is more, something like `raw/image/11`, `image/11?raw=true` seems like a good idea.

#

> The file size got bigger after downloading it. And the data has been changed

That should not happen. I'll look into this.

#

> Also the websocket connection doesn't seem to be working in the main domain, but it works fine with the websocket raw IP

Thanks for the heads up, now it works on `ws://ultrasc.tk:2095`

**Comment by TKperson** [comment]
Losing image token has already happened to me for 3 times and I have only uploaded 4 images (chance = 75% wow)
Can you save the image token in window.localStorage?

**Comment by DmitrijVC** [comment]
> Losing image token has already happened to me for 3 times and I have only uploaded 4 images (chance = 75% wow)
> Can you save the image token in window.localStorage?
> And a page for us to access the images/image token that are save in the localStorage

I was thinking about something like this.

# 

> Also I can see that you implemented all the meta tags for a lot of the apps (except discord). Can you also add those meta tags so the images will show up on discord?

This page was generated automatically. I also tried adding the meta tags for discord app, but it wasn't working. Someone told me that's because domains with suffixes like .tk are "banned on some applications?". I don't know how much truth it is in it, but I didn't manage to find any confirmation.

**Comment by TKperson** [comment]
Logo links to 404 page.

<img width="580" alt="Screenshot 2021-04-23 205716" src="https://user-images.githubusercontent.com/50115012/115946509-86d2f300-a476-11eb-8aec-cf0a2bcbeb4c.png">
